! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : iso_nox_Parameters.f90
! Time                 : Wed Jul 27 12:50:30 2022
! Working directory    : /home/disk/eos1/mwyant/isoprene/kpp-2.2.3/isopr_plus_NOx
! Equation file        : iso_nox.kpp
! Output root filename : iso_nox
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE chem_isoprene_Parameters

  ! USE chem_isoprene_Precision
  PUBLIC
  SAVE

! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 34 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 34 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 28 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 0
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 41 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 35 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 200 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 220 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 35 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 42 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 151 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)
  INTEGER, PARAMETER :: ind_H2O2 = 1
  INTEGER, PARAMETER :: ind_ROOH = 2
  INTEGER, PARAMETER :: ind_ISOP1OH = 3
  INTEGER, PARAMETER :: ind_ISOP1NitHP = 4
  INTEGER, PARAMETER :: ind_ISOPTHNit = 5
  INTEGER, PARAMETER :: ind_INRT = 6
  INTEGER, PARAMETER :: ind_CH4 = 7
  INTEGER, PARAMETER :: ind_Isoprene = 8
  INTEGER, PARAMETER :: ind_HNO3 = 9
  INTEGER, PARAMETER :: ind_DHHPEPOX = 10
  INTEGER, PARAMETER :: ind_PAN = 11
  INTEGER, PARAMETER :: ind_HNO4 = 12
  INTEGER, PARAMETER :: ind_ISOP1Nit = 13
  INTEGER, PARAMETER :: ind_IEPOX = 14
  INTEGER, PARAMETER :: ind_NO3 = 15
  INTEGER, PARAMETER :: ind_ISOPDHDHP = 16
  INTEGER, PARAMETER :: ind_ISOPDHHPNit = 17
  INTEGER, PARAMETER :: ind_ISOPTHHP = 18
  INTEGER, PARAMETER :: ind_CO = 19
  INTEGER, PARAMETER :: ind_O3 = 20
  INTEGER, PARAMETER :: ind_ISOPOOH = 21
  INTEGER, PARAMETER :: ind_C4CBYL = 22
  INTEGER, PARAMETER :: ind_ISOPDiNit = 23
  INTEGER, PARAMETER :: ind_HCHO = 24
  INTEGER, PARAMETER :: ind_C4CBYLNit = 25
  INTEGER, PARAMETER :: ind_ISOP1NitO2 = 26
  INTEGER, PARAMETER :: ind_ISOP1O2 = 27
  INTEGER, PARAMETER :: ind_ISOP2O2 = 28
  INTEGER, PARAMETER :: ind_C4CBYLO2 = 29
  INTEGER, PARAMETER :: ind_NO = 30
  INTEGER, PARAMETER :: ind_NO2 = 31
  INTEGER, PARAMETER :: ind_RO2 = 32
  INTEGER, PARAMETER :: ind_OH = 33
  INTEGER, PARAMETER :: ind_HO2 = 34

! Index declaration for fixed species in C
!   C(ind_spc)

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 78 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 157 

END MODULE chem_isoprene_Parameters

