! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (:,http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (:,http://www.gnu.org/copyleft/gpl.html)
! (:,C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (:,C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : iso_test_Function.f90
! Time                 : Sat Mar 12 20:02:40 2022
! Working directory    : /home/disk/eos6/mwyant/isoprene/kpp-2.2.3/variable_isoprene
! Equation file        : iso_test.kpp
! Output root filename : iso_test
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE chem_isoprene_Function

  USE chem_isoprene_Parameters
  IMPLICIT NONE


CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun - time derivatives of variables - Agregate form
!   Arguments :
!      V         - Concentrations of variable species (:,local)
!      F         - Concentrations of fixed species (:,local)
!      RCT       - Rate constants (:,local)
!      Vdot      - Time derivative of variable species concentrations
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun (nzm, V, F, RCT, Vdot )

  integer, intent(in) :: nzm
! V - Concentrations of variable species (:,local)
  REAL*8  :: V(nzm, NVAR)
! F - Concentrations of fixed species (:,local)
  REAL*8 :: F(nzm, NFIX)
! RCT - Rate constants (:,local)
  REAL*8 :: RCT(nzm, NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL*8 :: Vdot(nzm, NVAR)
! A - rate for each equation
  REAL*8 :: A(nzm, NREACT)

  integer :: k, n


! Computation of equation rates
  A(:,1) = RCT(:,1)*V(:,8)*V(:,33)
  A(:,2) = RCT(:,2)*V(:,27)*V(:,34)
  A(:,3) = RCT(:,3)*V(:,27)*V(:,30)
  A(:,4) = 1e-12*V(:,27)*V(:,32)
  A(:,5) = 1e-12*V(:,27)*V(:,27)
  A(:,6) = 1.54e-10*V(:,21)*V(:,33)
  A(:,7) = RCT(:,7)*V(:,28)
  A(:,8) = RCT(:,8)*V(:,28)*V(:,34)
  A(:,9) = RCT(:,9)*V(:,28)*V(:,30)
  A(:,10) = 1e-12*V(:,28)*V(:,32)
  A(:,11) = 2.17e-11*V(:,13)*V(:,33)
  A(:,12) = RCT(:,12)*V(:,26)*V(:,34)
  A(:,13) = RCT(:,13)*V(:,26)*V(:,30)
  A(:,14) = 1e-12*V(:,26)*V(:,32)
  A(:,15) = 8.4e-12*V(:,14)*V(:,33)
  A(:,16) = 8.4e-12*V(:,10)*V(:,33)
  A(:,17) = RCT(:,17)*V(:,22)*V(:,33)
  A(:,18) = RCT(:,18)*V(:,29)*V(:,31)
  A(:,19) = RCT(:,19)*V(:,11)
  A(:,20) = RCT(:,20)*V(:,29)*V(:,30)
  A(:,21) = 1.63e-12*V(:,23)*V(:,33)
  A(:,22) = RCT(:,22)*V(:,16)*V(:,33)
  A(:,23) = RCT(:,23)*V(:,25)*V(:,33)
  A(:,24) = RCT(:,24)*V(:,17)*V(:,33)
  A(:,25) = RCT(:,25)*V(:,18)*V(:,33)
  A(:,26) = RCT(:,26)*V(:,20)*V(:,30)
  A(:,27) = RCT(:,27)*V(:,20)*V(:,33)
  A(:,28) = RCT(:,28)*V(:,20)*V(:,34)
  A(:,29) = RCT(:,29)*V(:,30)*V(:,34)
  A(:,30) = RCT(:,30)*V(:,31)*V(:,33)
  A(:,31) = RCT(:,31)*V(:,9)*V(:,33)
  A(:,32) = RCT(:,32)*V(:,15)*V(:,30)
  A(:,33) = RCT(:,33)*V(:,31)*V(:,34)
  A(:,34) = RCT(:,34)*V(:,12)*V(:,33)
  A(:,35) = RCT(:,35)*V(:,33)*V(:,34)
  A(:,36) = RCT(:,36)*V(:,24)*V(:,33)
  A(:,37) = RCT(:,37)*V(:,34)*V(:,34)
  A(:,38) = RCT(:,38)*V(:,19)*V(:,33)
  A(:,39) = RCT(:,39)*V(:,7)*V(:,33)
  A(:,40) = RCT(:,40)*V(:,32)*V(:,34)
  A(:,41) = RCT(:,41)*V(:,30)*V(:,32)

! Aggregate function
  Vdot(:,1) = A(:,37)
  Vdot(:,2) = A(:,40)
  Vdot(:,3) = 0.3*A(:,4)
  Vdot(:,4) = A(:,12)
  Vdot(:,5) = 0.3*A(:,14)
  Vdot(:,6) = A(:,35)
  Vdot(:,7) = -A(:,39)
  Vdot(:,8) = -A(:,1)
  Vdot(:,9) = A(:,30)-A(:,31)
  Vdot(:,10) = A(:,7)-A(:,16)
  Vdot(:,11) = A(:,18)-A(:,19)
  Vdot(:,12) = A(:,33)-A(:,34)
  Vdot(:,13) = 0.105*A(:,3)-A(:,11)
  Vdot(:,14) = 0.7*A(:,6)-A(:,15)
  Vdot(:,15) = A(:,31)-A(:,32)
  Vdot(:,16) = A(:,8)-A(:,22)
  Vdot(:,17) = 0.13*A(:,9)-A(:,24)
  Vdot(:,18) = 0.3*A(:,10)-A(:,25)
  Vdot(:,19) = 2*A(:,5)+1.86*A(:,20)+2*A(:,23)+A(:,36)-A(:,38)
  Vdot(:,20) = -A(:,26)-A(:,27)-A(:,28)
  Vdot(:,21) = A(:,2)-A(:,6)
  Vdot(:,22) = 0.896*A(:,3)+0.7*A(:,4)+2*A(:,5)+0.87*A(:,9)+0.7*A(:,10)+A(:,15)+A(:,16)-A(:,17)+A(:,22)+A(:,25)
  Vdot(:,23) = 0.16*A(:,13)-A(:,21)
  Vdot(:,24) = 0.896*A(:,3)+0.87*A(:,9)+0.7*A(:,10)+0.84*A(:,13)+0.7*A(:,14)+A(:,15)+A(:,16)+1.86*A(:,20)+A(:,21)+A(:,22)+2*A(:,23)+A(:,24)+A(:,25)-A(:,36)+A(:,41)
  Vdot(:,25) = 0.84*A(:,13)+0.7*A(:,14)+0.07*A(:,20)+A(:,21)-A(:,23)+A(:,24)
  Vdot(:,26) = A(:,11)-A(:,12)-A(:,13)-A(:,14)
  Vdot(:,27) = A(:,1)-A(:,2)-A(:,3)-A(:,4)-2*A(:,5)
  Vdot(:,28) = 0.3*A(:,6)-A(:,7)-A(:,8)-A(:,9)-A(:,10)
  Vdot(:,29) = A(:,17)-A(:,18)-A(:,20)
  Vdot(:,30) = -A(:,3)-A(:,9)-A(:,13)-A(:,20)-A(:,26)-A(:,29)-A(:,32)-A(:,41)
  Vdot(:,31) = 0.896*A(:,3)+0.87*A(:,9)+0.84*A(:,13)-A(:,18)+A(:,19)+0.93*A(:,20)+A(:,21)+A(:,23)+A(:,26)+A(:,29)-A(:,30)+2*A(:,32)-A(:,33)+A(:,34)+A(:,41)
  Vdot(:,32) = -A(:,4)-A(:,10)-A(:,14)+A(:,19)+A(:,39)-A(:,40)-A(:,41)
  Vdot(:,33) = -A(:,1)-0.3*A(:,6)+A(:,7)-A(:,11)-A(:,15)-A(:,17)-A(:,21)-A(:,22)-A(:,23)-A(:,24)-A(:,5)-A(:,27)+A(:,28)+A(:,29)-A(:,30)-A(:,31)-A(:,34)-A(:,35)-A(:,36)-A(:,38)-A(:,39)
  Vdot(:,34) = -A(:,2)+0.896*A(:,3)+0.4*A(:,4)+2*A(:,5)-A(:,8)-A(:,12)+0.93*A(:,20)+A(:,21)+A(:,23)+A(:,27)-A(:,28)-A(:,29)-A(:,33)-A(:,35)+A(:,36)-2*A(:,37)+A(:,38)-A(:,40)

  do k = 1, 100
    do n = 1, 34
        if ( isnan(Vdot(k, n)) ) then
          print*, "THERE IS A NAN! THERE IS A NAN! IN KPP", Vdot(k, n)
          print*, "k=", k 
          print*, "n=", n 

          print*, "test_carbon_monoxide=", A(k,30)
          print*, "RCT=", RCT(k,30)
          print*, "V1=", V(k,31)
          print*, "V2=", V(k,33)
          print*, "test_nitric_acid_2=", A(k,31)
          print*, "RCT=", RCT(k,31)
          print*, "V1=", V(k,33)
          print*, "V2=", V(k,9)
          STOP
        endif
    enddo
  enddo
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

END MODULE chem_isoprene_Function

