! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : chem_isoprene_Monitor.f90
! Time                 : Sat Mar 12 20:02:40 2022
! Working directory    : /home/disk/eos6/mwyant/isoprene/kpp-2.2.3/variable_isoprene
! Equation file        : iso_test.kpp
! Output root filename : iso_test
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE chem_isoprene_Monitor

   CHARACTER(LEN=15), PARAMETER, DIMENSION(34) :: SPC_NAMES = (/ &
   'H2O2','ROOH','ISOP1OH','ISOP1NitHP','ISOPTHNit', &
   'INRT','CH4','Isoprene','HNO3','DHHPEPOX', &
   'PAN','HNO4','ISOP1Nit','IEPOX','NO3', &
   'ISOPDHDHP','ISOPDHHPNit','ISOPTHHP','CO','O3', & 
   'ISOPOOH','C4CBYL','ISOPDiNit','HCHO','C4CBYLNit', &
   'ISOP1NitO2','ISOP1O2','ISOP2O2','C4CBYLO2','NO', &
   'NO2','RO2','OH','HO2' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(41) :: EQN_NAMES = (/ &
      '   Isoprene + OH --> ISOP1O2                          ', &
      '   ISOP1O2 + HO2 --> ISOPOOH                          ', &
      '    ISOP1O2 + NO --> 0.105 ISOP1Nit + 0.896 C4CBYL + 0', &
      '   ISOP1O2 + RO2 --> 0.3 ISOP1OH + 0.7 C4CBYL + 0.4 HO', &
      '       2 ISOP1O2 --> 2 CO + 2 C4CBYL + 2 HO2          ', &
      '    ISOPOOH + OH --> 0.7 IEPOX + 0.3 ISOP2O2 + 0.7 OH ', &
      '         ISOP2O2 --> DHHPEPOX + OH                    ', &
      '   ISOP2O2 + HO2 --> ISOPDHDHP                        ', &
      '    ISOP2O2 + NO --> 0.13 ISOPDHHPNit + 0.87 C4CBYL + ', &
      '   ISOP2O2 + RO2 --> 0.3 ISOPTHHP + 0.7 C4CBYL + 0.7 H', &
      '   ISOP1Nit + OH --> ISOP1NitO2                       ', &
      'ISOP1NitO2 + HO2 --> ISOP1NitHP                       ', &
      ' ISOP1NitO2 + NO --> 0.16 ISOPDiNit + 0.84 HCHO + 0.84', &
      'ISOP1NitO2 + RO2 --> 0.3 ISOPTHNit + 0.7 HCHO + 0.7 C4', &
      '      IEPOX + OH --> C4CBYL + HCHO                    ', &
      '   DHHPEPOX + OH --> C4CBYL + HCHO + OH               ', &
      '     C4CBYL + OH --> C4CBYLO2                         ', &
      '  C4CBYLO2 + NO2 --> PAN                              ', &
      '             PAN --> NO2 + RO2                        ', &
      '   C4CBYLO2 + NO --> 1.86 CO + 1.86 HCHO + 0.07 C4CBYL', &
      '  ISOPDiNit + OH --> HCHO + C4CBYLNit + NO2 + HO2     ', &
      '  ISOPDHDHP + OH --> C4CBYL + HCHO                    ', &
      '  C4CBYLNit + OH --> 2 CO + 2 HCHO + NO2 + HO2        ', &
      'ISOPDHHPNit + OH --> HCHO + C4CBYLNit                 ', &
      '   ISOPTHHP + OH --> C4CBYL + HCHO                    ', &
      '         O3 + NO --> NO2                              ', &
      '         O3 + OH --> HO2                              ', &
      '        O3 + HO2 --> OH                               ', &
      '        NO + HO2 --> NO2 + OH                         ', &
      '        NO2 + OH --> HNO3                             ', &
      '       HNO3 + OH --> NO3                              ', &
      '        NO3 + NO --> 2 NO2                            ', &
      '       NO2 + HO2 --> HNO4                             ', &
      '       HNO4 + OH --> NO2                              ', &
      '        OH + HO2 --> INRT                             ', &
      '       HCHO + OH --> CO + HO2                         ', &
      '           2 HO2 --> H2O2                             ', &
      '         CO + OH --> HO2                              ', &
      '        CH4 + OH --> RO2                              ', &
      '       RO2 + HO2 --> ROOH                             ', &
      '        NO + RO2 --> HCHO + NO2                       ' /)

! INLINED global variables
! End INLINED global variables


END MODULE chem_isoprene_Monitor
