! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : iso_nox_Parameters.f90
! Time                 : Wed Jul 27 12:50:30 2022
! Working directory    : /home/disk/eos1/mwyant/isoprene/kpp-2.2.3/isopr_plus_NOx
! Equation file        : iso_nox.kpp
! Output root filename : iso_nox
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE iso_nox_Parameters

  USE iso_nox_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 28 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 23 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 18 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 5 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 27 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 24 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 88 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 94 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 24 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 28 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 30 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_Isoprene = 1 
  INTEGER, PARAMETER :: ind_HCHO = 2 
  INTEGER, PARAMETER :: ind_CO = 3 
  INTEGER, PARAMETER :: ind_ISOP1OH = 4 
  INTEGER, PARAMETER :: ind_ISOP1NitHP = 5 
  INTEGER, PARAMETER :: ind_ISOPTHNit = 6 
  INTEGER, PARAMETER :: ind_DHHPEPOX = 7 
  INTEGER, PARAMETER :: ind_ISOPDHDHP = 8 
  INTEGER, PARAMETER :: ind_ISOPTHHP = 9 
  INTEGER, PARAMETER :: ind_IEPOX = 10 
  INTEGER, PARAMETER :: ind_PAN = 11 
  INTEGER, PARAMETER :: ind_ISOPOOH = 12 
  INTEGER, PARAMETER :: ind_ISOP1Nit = 13 
  INTEGER, PARAMETER :: ind_ISOPDHHPNit = 14 
  INTEGER, PARAMETER :: ind_C4CBYL = 15 
  INTEGER, PARAMETER :: ind_ISOPDiNit = 16 
  INTEGER, PARAMETER :: ind_C4CBYLNit = 17 
  INTEGER, PARAMETER :: ind_ISOP1NitO2 = 18 
  INTEGER, PARAMETER :: ind_ISOP1O2 = 19 
  INTEGER, PARAMETER :: ind_NO2 = 20 
  INTEGER, PARAMETER :: ind_C4CBYLO2 = 21 
  INTEGER, PARAMETER :: ind_NO = 22 
  INTEGER, PARAMETER :: ind_ISOP2O2 = 23 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_OH = 24 
  INTEGER, PARAMETER :: ind_RO2 = 25 
  INTEGER, PARAMETER :: ind_HO2 = 26 
  INTEGER, PARAMETER :: ind_O3 = 27 
  INTEGER, PARAMETER :: ind_O2 = 28 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_OH = 1 
  INTEGER, PARAMETER :: indf_RO2 = 2 
  INTEGER, PARAMETER :: indf_HO2 = 3 
  INTEGER, PARAMETER :: indf_O3 = 4 
  INTEGER, PARAMETER :: indf_O2 = 5 

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 32 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 87 

END MODULE iso_nox_Parameters

