! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : iso_nox_Monitor.f90
! Time                 : Wed Jul 27 12:50:30 2022
! Working directory    : /home/disk/eos1/mwyant/isoprene/kpp-2.2.3/isopr_plus_NOx
! Equation file        : iso_nox.kpp
! Output root filename : iso_nox
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE iso_nox_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(28) :: SPC_NAMES = (/ &
     'Isoprene       ','HCHO           ','CO             ', &
     'ISOP1OH        ','ISOP1NitHP     ','ISOPTHNit      ', &
     'DHHPEPOX       ','ISOPDHDHP      ','ISOPTHHP       ', &
     'IEPOX          ','PAN            ','ISOPOOH        ', &
     'ISOP1Nit       ','ISOPDHHPNit    ','C4CBYL         ', &
     'ISOPDiNit      ','C4CBYLNit      ','ISOP1NitO2     ', &
     'ISOP1O2        ','NO2            ','C4CBYLO2       ', &
     'NO             ','ISOP2O2        ','OH             ', &
     'RO2            ','HO2            ','O3             ', &
     'O2             ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(27) :: EQN_NAMES = (/ &
     '   Isoprene + OH --> ISOP1O2                                                                        ', &
     '   ISOP1O2 + HO2 --> ISOPOOH                                                                        ', &
     '    ISOP1O2 + NO --> 0.896 HCHO + 0.105 ISOP1Nit + 0.896 C4CBYL + 0.896 NO2 ... etc.                ', &
     '   ISOP1O2 + RO2 --> 0.3 ISOP1OH + 0.7 C4CBYL + 0.4 HO2                                             ', &
     '       2 ISOP1O2 --> 2 CO + 2 C4CBYL + 2 HO2                                                        ', &
     '    ISOPOOH + OH --> 0.7 IEPOX + 0.3 ISOP2O2 + 0.7 OH                                               ', &
     '         ISOP2O2 --> DHHPEPOX + OH                                                                  ', &
     '   ISOP2O2 + HO2 --> ISOPDHDHP                                                                      ', &
     '    NO + ISOP2O2 --> 0.87 HCHO + 0.13 ISOPDHHPNit + 0.87 C4CBYL + 0.87 NO2 ... etc.                 ', &
     '   ISOP2O2 + RO2 --> 0.7 HCHO + 0.3 ISOPTHHP + 0.7 C4CBYL                                           ', &
     '   ISOP1Nit + OH --> ISOP1NitO2                                                                     ', &
     'ISOP1NitO2 + HO2 --> ISOP1NitHP                                                                     ', &
     ' ISOP1NitO2 + NO --> 0.84 HCHO + 0.16 ISOPDiNit + 0.84 C4CBYLNit + 0.84 NO2 ... etc.                ', &
     'ISOP1NitO2 + RO2 --> 0.7 HCHO + 0.3 ISOPTHNit + 0.7 C4CBYLNit                                       ', &
     '      IEPOX + OH --> HCHO + C4CBYL                                                                  ', &
     '   DHHPEPOX + OH --> HCHO + C4CBYL + OH                                                             ', &
     '     C4CBYL + OH --> C4CBYLO2                                                                       ', &
     '  NO2 + C4CBYLO2 --> PAN                                                                            ', &
     '             PAN --> NO2 + RO2                                                                      ', &
     '   C4CBYLO2 + NO --> 1.86 HCHO + 1.86 CO + 0.07 C4CBYLNit + 0.93 NO2 + 0.93 HO2 ... etc.            ', &
     '  ISOPDiNit + OH --> HCHO + C4CBYLNit + NO2 + HO2                                                   ', &
     '  ISOPDHDHP + OH --> HCHO + C4CBYL                                                                  ', &
     '  C4CBYLNit + OH --> 2 HCHO + 2 CO + NO2 + HO2                                                      ', &
     'ISOPDHHPNit + OH --> HCHO + C4CBYLNit                                                               ', &
     '   ISOPTHHP + OH --> HCHO + C4CBYL                                                                  ', &
     '         NO + O3 --> NO2 + O2                                                                       ', &
     '        NO + HO2 --> NO2 + O2                                                                       ' /)

! INLINED global variables

! End INLINED global variables


END MODULE iso_nox_Monitor
