! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : iso_nox_Function.f90
! Time                 : Wed Jul 27 12:50:30 2022
! Working directory    : /home/disk/eos1/mwyant/isoprene/kpp-2.2.3/isopr_plus_NOx
! Equation file        : iso_nox.kpp
! Output root filename : iso_nox
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE iso_nox_Function

  USE iso_nox_Parameters
  IMPLICIT NONE

! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun - time derivatives of variables - Agregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)


! Computation of equation rates
  A(1) = RCT(1)*V(1)*F(1)
  A(2) = RCT(2)*V(19)*F(3)
  A(3) = RCT(3)*V(19)*V(22)
  A(4) = 1e-12*V(19)*F(2)
  A(5) = 1e-12*V(19)*V(19)
  A(6) = 1.54e-10*V(12)*F(1)
  A(7) = RCT(7)*V(23)
  A(8) = RCT(8)*V(23)*F(3)
  A(9) = RCT(9)*V(22)*V(23)
  A(10) = 1e-12*V(23)*F(2)
  A(11) = 2.17e-11*V(13)*F(1)
  A(12) = RCT(12)*V(18)*F(3)
  A(13) = RCT(13)*V(18)*V(22)
  A(14) = 1e-12*V(18)*F(2)
  A(15) = 8.4e-12*V(10)*F(1)
  A(16) = 8.4e-12*V(7)*F(1)
  A(17) = RCT(17)*V(15)*F(1)
  A(18) = RCT(18)*V(20)*V(21)
  A(19) = RCT(19)*V(11)
  A(20) = RCT(20)*V(21)*V(22)
  A(21) = 1.63e-12*V(16)*F(1)
  A(22) = RCT(22)*V(8)*F(1)
  A(23) = RCT(23)*V(17)*F(1)
  A(24) = RCT(24)*V(14)*F(1)
  A(25) = RCT(25)*V(9)*F(1)
  A(26) = RCT(26)*V(22)*F(4)
  A(27) = RCT(27)*V(22)*F(3)

! Aggregate function
  Vdot(1) = -A(1)
  Vdot(2) = 0.896*A(3)+0.87*A(9)+0.7*A(10)+0.84*A(13)+0.7*A(14)+A(15)+A(16)+1.86*A(20)+A(21)+A(22)+2*A(23)+A(24)+A(25)
  Vdot(3) = 2*A(5)+1.86*A(20)+2*A(23)
  Vdot(4) = 0.3*A(4)
  Vdot(5) = A(12)
  Vdot(6) = 0.3*A(14)
  Vdot(7) = A(7)-A(16)
  Vdot(8) = A(8)-A(22)
  Vdot(9) = 0.3*A(10)-A(25)
  Vdot(10) = 0.7*A(6)-A(15)
  Vdot(11) = A(18)-A(19)
  Vdot(12) = A(2)-A(6)
  Vdot(13) = 0.105*A(3)-A(11)
  Vdot(14) = 0.13*A(9)-A(24)
  Vdot(15) = 0.896*A(3)+0.7*A(4)+2*A(5)+0.87*A(9)+0.7*A(10)+A(15)+A(16)-A(17)+A(22)+A(25)
  Vdot(16) = 0.16*A(13)-A(21)
  Vdot(17) = 0.84*A(13)+0.7*A(14)+0.07*A(20)+A(21)-A(23)+A(24)
  Vdot(18) = A(11)-A(12)-A(13)-A(14)
  Vdot(19) = A(1)-A(2)-A(3)-A(4)-2*A(5)
  Vdot(20) = 0.896*A(3)+0.87*A(9)+0.84*A(13)-A(18)+A(19)+0.93*A(20)+A(21)+A(23)+A(26)+A(27)
  Vdot(21) = A(17)-A(18)-A(20)
  Vdot(22) = -A(3)-A(9)-A(13)-A(20)-A(26)-A(27)
  Vdot(23) = 0.3*A(6)-A(7)-A(8)-A(9)-A(10)
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE iso_nox_Function

