! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.3 symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : iso_test_Parameters.f90
! Time                 : Sat Mar 12 20:02:40 2022
! Working directory    : /home/disk/eos6/mwyant/isoprene/kpp-2.2.3/variable_isoprene
! Equation file        : iso_test.kpp
! Output root filename : iso_test
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE chem_isoprene_Parameters

!  USE chem_isoprene_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 26 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 21 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 16 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 5 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 25 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 22 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 61 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 61 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 22 
! CNEQN - (NREACT+1) Number stoicm elements in compressed col format
  INTEGER, PARAMETER :: CNEQN = 26 
! NHESS - Length of Sparse Hessian
  INTEGER, PARAMETER :: NHESS = 3 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_PAN = 1 
  INTEGER, PARAMETER :: ind_Isoprene = 2 
  INTEGER, PARAMETER :: ind_ISOP1O2 = 3 
  INTEGER, PARAMETER :: ind_ISOP1Nit = 4 
  INTEGER, PARAMETER :: ind_ISOP1NitO2 = 5 
  INTEGER, PARAMETER :: ind_ISOPDiNit = 6 
  INTEGER, PARAMETER :: ind_ISOPOOH = 7 
  INTEGER, PARAMETER :: ind_IEPOX = 8 
  INTEGER, PARAMETER :: ind_ISOP2O2 = 9 
  INTEGER, PARAMETER :: ind_ISOPTHHP = 10 
  INTEGER, PARAMETER :: ind_ISOPDHDHP = 11 
  INTEGER, PARAMETER :: ind_ISOPDHHPNit = 12 
  INTEGER, PARAMETER :: ind_DHHPEPOX = 13 
  INTEGER, PARAMETER :: ind_C4CBYL = 14 
  INTEGER, PARAMETER :: ind_C4CBYLO2 = 15 
  INTEGER, PARAMETER :: ind_C4CBYLNit = 16 
  INTEGER, PARAMETER :: ind_HCHO = 17 
  INTEGER, PARAMETER :: ind_CO = 18 
  INTEGER, PARAMETER :: ind_ISOP1OH = 19 
  INTEGER, PARAMETER :: ind_ISOP1NitHP = 20 
  INTEGER, PARAMETER :: ind_ISOPTHNit = 21 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_OH = 22 
  INTEGER, PARAMETER :: ind_NO = 23 
  INTEGER, PARAMETER :: ind_NO2 = 24 
  INTEGER, PARAMETER :: ind_RO2 = 25 
  INTEGER, PARAMETER :: ind_HO2 = 26 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_OH = 1 
  INTEGER, PARAMETER :: indf_NO = 2 
  INTEGER, PARAMETER :: indf_NO2 = 3 
  INTEGER, PARAMETER :: indf_RO2 = 4 
  INTEGER, PARAMETER :: indf_HO2 = 5 

! NJVRP - Length of sparse Jacobian JVRP
  INTEGER, PARAMETER :: NJVRP = 25 

! NSTOICM - Length of Sparse Stoichiometric Matrix
  INTEGER, PARAMETER :: NSTOICM = 71 

END MODULE chem_isoprene_Parameters

