! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-3.3.0 symbolic chemistry Kinetics PreProcessor
!       (https:/github.com/KineticPreProcessor/KPP
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2022, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian,   Villanova University, Philadelphia, PA, USA
!        R. Sander,   Max-Planck Institute for Chemistry, Mainz, Germany
!        M. Long,     Renaissance Fiber, LLC, North Carolina, USA
!        H. Lin,      Harvard University, Cambridge, MA, USA
!        R. Yantosca, Harvard University, Cambridge, MA, USA
! 
! File                 : cloudchem_JacobianSP.F90
! Equation file        : cloudchem.kpp
! Output root filename : cloudchem
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE cloudchem_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(234) :: LU_IROW = (/ &
       1,  2,  2,  2,  3,  3,  3,  4,  4,  4,  5,  5, & ! index 1 - 12
       5,  6,  6,  6,  7,  7,  8,  8,  9,  9,  9, 10, & ! index 13 - 24
      10, 10, 11, 11, 11, 12, 12, 12, 13, 13, 13, 14, & ! index 25 - 36
      14, 14, 14, 14, 14, 15, 15, 15, 15, 16, 16, 16, & ! index 37 - 48
      16, 17, 17, 17, 17, 18, 18, 18, 18, 19, 19, 19, & ! index 49 - 60
      19, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, 20, & ! index 61 - 72
      20, 21, 21, 21, 21, 21, 21, 21, 22, 22, 22, 22, & ! index 73 - 84
      23, 23, 23, 23, 23, 23, 24, 24, 24, 24, 24, 25, & ! index 85 - 96
      25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, & ! index 97 - 108
      25, 25, 25, 25, 26, 26, 26, 26, 26, 26, 26, 26, & ! index 109 - 120
      26, 27, 27, 27, 27, 27, 27, 27, 27, 27, 28, 28, & ! index 121 - 132
      28, 28, 28, 28, 28, 29, 29, 29, 29, 29, 29, 29, & ! index 133 - 144
      29, 29, 30, 30, 30, 30, 30, 30, 30, 30, 30, 30, & ! index 145 - 156
      30, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, 31, & ! index 157 - 168
      32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, 32, & ! index 169 - 180
      32, 32, 32, 33, 33, 33, 33, 33, 33, 33, 33, 34, & ! index 181 - 192
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, & ! index 193 - 204
      34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, 34, & ! index 205 - 216
      34, 34, 34, 35, 35, 35, 35, 35, 35, 35, 35, 35, & ! index 217 - 228
      35, 35, 35, 35, 35, 35 /) ! index up to 234

  INTEGER, PARAMETER, DIMENSION(234) :: LU_ICOL = (/ &
       1,  2, 30, 35,  3, 30, 33,  4, 27, 35,  5, 27, & ! index 1 - 12
      30,  6, 34, 35,  7, 35,  8, 34,  9, 32, 34, 10, & ! index 13 - 24
      28, 34, 11, 29, 32, 12, 19, 34, 13, 23, 34, 13, & ! index 25 - 36
      14, 23, 31, 33, 34, 15, 32, 34, 35, 16, 28, 34, & ! index 37 - 48
      35, 17, 28, 31, 34, 18, 28, 30, 34, 19, 33, 34, & ! index 49 - 60
      35, 10, 12, 16, 18, 19, 20, 28, 30, 31, 33, 34, & ! index 61 - 72
      35, 21, 25, 26, 29, 31, 33, 34, 22, 27, 31, 34, & ! index 73 - 84
       9, 13, 23, 31, 32, 34, 24, 31, 32, 34, 35, 10, & ! index 85 - 96
      12, 16, 17, 18, 19, 22, 25, 26, 27, 28, 29, 30, & ! index 97 - 108
      31, 33, 34, 35, 17, 22, 26, 27, 28, 29, 30, 31, & ! index 109 - 120
      34, 14, 23, 27, 30, 31, 32, 33, 34, 35, 19, 28, & ! index 121 - 132
      30, 31, 33, 34, 35, 20, 28, 29, 30, 31, 32, 33, & ! index 133 - 144
      34, 35,  8, 11, 27, 28, 29, 30, 31, 32, 33, 34, & ! index 145 - 156
      35, 23, 24, 27, 28, 29, 30, 31, 32, 33, 34, 35, & ! index 157 - 168
      11, 15, 22, 23, 24, 26, 27, 28, 29, 30, 31, 32, & ! index 169 - 180
      33, 34, 35, 13, 23, 30, 31, 32, 33, 34, 35,  1, & ! index 181 - 192
       7,  8,  9, 12, 13, 14, 15, 16, 17, 18, 19, 20, & ! index 193 - 204
      21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, & ! index 205 - 216
      33, 34, 35, 15, 21, 22, 24, 25, 26, 27, 28, 29, & ! index 217 - 228
      30, 31, 32, 33, 34, 35 /) ! index up to 234

  INTEGER, PARAMETER, DIMENSION(36) :: LU_CROW = (/ &
       1,  2,  5,  8, 11, 14, 17, 19, 21, 24, 27, 30, & ! index 1 - 12
      33, 36, 42, 46, 50, 54, 58, 62, 74, 81, 85, 91, & ! index 13 - 24
      96,113,122,131,138,147,158,169,184,192,220,235 /) ! index up to 36

  INTEGER, PARAMETER, DIMENSION(36) :: LU_DIAG = (/ &
       1,  2,  5,  8, 11, 14, 17, 19, 21, 24, 27, 30, & ! index 1 - 12
      33, 37, 42, 46, 50, 54, 58, 67, 74, 81, 87, 91, & ! index 13 - 24
     103,115,124,132,140,152,164,180,189,218,234,235 /) ! index up to 36


END MODULE cloudchem_JacobianSP

